### ISSUE TITLE
Primary Identifier question

### ISSUE THREAD

**Issue by zanven42** [gobranch/cfn-ssm-parameter-value-resource#1]
Just wondering if it would make sense to make the primary "Value" so !Ref gets the most likely used variable by default. 

Not sure how to best use Primary Identifier but my understanding would be to try and set that to the most likely used value in other parts of cloudformation.

**Comment by tallpants** [comment]
@zanven42 this is just an example repo, we aren't planning on maintaining it -- and you definitely shouldn't use it in production. If you want to reference SSM Parameter Store values in your template use them as CloudFormation parameters like the docs here describe: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types

For your question specifically, my understanding is that the primary identifier is what's used to uniquely identify the resource itself, while the value is a property of the resource. i.e the resource is the key and the value is a property -- so the value can change while the key itself continues to exist as the same key.

I could definitely be wrong though, I think the appropriate people to ask about this are the CloudFormation people themselves: https://github.com/aws-cloudformation/cloudformation-cli
